const iconWeather = {
  0: '/icon/weather/sun.svg',
  1: '/icon/weather/cloudySun.svg',
  2: '/icon/weather/cloudySun.svg',
  3: '/icon/weather/cloudy.svg',
  45: '/icon/weather/rain.svg',
  48: '/icon/weather/rain.svg',
  51: '/icon/weather/rain.svg',
  53: '/icon/weather/rain.svg',
  55: '/icon/weather/rain.svg',
  56: '/icon/weather/rain.svg',
  57: '/icon/weather/rain.svg',
  61: '/icon/weather/rain.svg',
  63: '/icon/weather/rain.svg',
  65: '/icon/weather/rain.svg',
  66: '/icon/weather/snow.svg',
  67: '/icon/weather/snow.svg',
  71: '/icon/weather/snow.svg',
  73: '/icon/weather/snow.svg',
  75: '/icon/weather/snow.svg',
  77: '/icon/weather/snow.svg',
  86: '/icon/weather/snow.svg',
  85: '/icon/weather/snow.svg',
  80: '/icon/weather/rain.svg',
  81: '/icon/weather/rain.svg',
  82: '/icon/weather/rain.svg',
  95: '/icon/weather/rain.svg',
  96: '/icon/weather/rain.svg',
  99: '/icon/weather/rain.svg',
};

export default iconWeather;
