// Словарь иконок сообщений, выбирается по msg.code или msg.order
// order, code => соответствуют back\src\dict\message\index.js
const iconIncident = {
  undefined: '/icon/incident/signal-info.svg',
  null: '/icon/incident/signal-info.svg',
  '': '/icon/incident/signal-info.svg',

  // warning Предупреждление
  antibliz: '/icon/incident/warning/antibliz.svg',
  debdo: '/icon/incident/warning/debdo.svg',
  openVin: '/icon/incident/warning/open-vin.svg',
  overVlv: '/icon/incident/warning/over-vlv.svg',
  stableVno: '/icon/incident/warning/stable-vno.svg',
  30: '/icon/incident/warning/long.svg',
  31: '/icon/incident/warning/long.svg',
  t_channel: '/icon/incident/warning/signal.svg',
  41: '/icon/incident/warning/signal.svg',
  65: '/icon/incident/warning/signal.svg',
  104: '/icon/incident/warning/signal.svg',
  105: '/icon/incident/warning/signal.svg',

  //   equipment Работа оборудования
  //   Таймеры запретов
  drying: '/icon/incident/notification/drying.svg',
  cure: '/icon/incident/notification/cure.svg',
  cooling: '/icon/incident/notification/cooling.svg',
  heat: '/icon/incident/notification/heat.svg',
  vent: '/icon/incident/notification/vent.svg',
  accel: '/icon/incident/notification/accel.svg',
  ozon: '/icon/incident/notification/ozon.svg',
  heater: '/icon/incident/notification/heater.svg',
  co2: '/icon/incident/notification/co2.svg',
  wetting: '/icon/incident/notification/wetting.svg',

  smoking1: '/icon/incident/equipment/smoking1.svg',
  smoking2: '/icon/incident/equipment/smoking2.svg',

  check_supply: '',
  demo: '',
  50: '/icon/incident/alarm/connect.svg',
  51: '/icon/incident/equipment/accel.svg',
  52: '/icon/incident/equipment/accel.svg',
  53: '/icon/incident/equipment/accel.svg',
  54: '/icon/incident/equipment/accel.svg',
  83: '/icon/incident/equipment/accel.svg',
  55: '',
  121: '',
  122: '',
  123: '',
  124: '',
  125: '',
  126: '/icon/incident/equipment/heater.svg',
  127: '/icon/incident/equipment/heater.svg',
  128: '/icon/incident/equipment/heater.svg',
  129: '/icon/incident/equipment/heater.svg',
  161: '/icon/incident/equipment/heater.svg',
  162: '/icon/incident/equipment/heater.svg',
  163: '/icon/incident/equipment/heater.svg',
  130: '/icon/incident/equipment/wetting.svg',
  131: '/icon/incident/equipment/wetting.svg',
  132: '/icon/incident/equipment/wetting.svg',
  133: '/icon/incident/equipment/wetting.svg',
  134: '/icon/incident/equipment/wetting.svg',
  135: '/icon/incident/equipment/wetting.svg',
  136: '/icon/incident/equipment/wetting.svg',
  137: '/icon/incident/equipment/wetting.svg',
  138: '/icon/incident/equipment/wetting.svg',
  138: '/icon/incident/equipment/wetting.svg',
  140: '/icon/incident/equipment/wetting.svg',
  141: '/icon/incident/equipment/wetting.svg',
  160: '',
  59: '',
  //   vent
  ventDura: '/icon/incident/equipment/vent-dura.svg',
  ventOn: '/icon/incident/equipment/vent-on.svg',
  ventTime: '/icon/incident/equipment/ventTime.svg',
  ventTimeWait: '/icon/incident/equipment/vent-time-wait.svg',
  87: '/icon/incident/equipment/vent-time-wait.svg',
  88: '/icon/incident/equipment/vent-on.svg',
  89: '/icon/incident/equipment/vent-time-wait.svg',
  142: '/icon/incident/equipment/vent-on.svg',
  143: '/icon/incident/equipment/vent-on.svg',
  144: '/icon/incident/equipment/vent-on.svg',
  145: '/icon/incident/equipment/vent-on.svg',
  146: '/icon/incident/equipment/vent-time.svg',
  147: '/icon/incident/equipment/vent-on.svg',
  148: '/icon/incident/equipment/vent-dura.svg',
  149: '/icon/incident/equipment/vent-dura.svg',
  //   co2
  61: '/icon/incident/equipment/co2.svg',
  62: '/icon/incident/equipment/co2.svg',
  63: '/icon/incident/equipment/co2.svg',
  64: '/icon/incident/equipment/co2.svg',
  84: '/icon/incident/equipment/co2work.svg',
  85: '/icon/incident/equipment/co2wait.svg',
  86: '/icon/incident/equipment/co2.svg',

  67: '',
  68: '',
  69: '',
  70: '',
  71: '',
  72: '',
  82: '/icon/incident/equipment/smoking1.svg',
  91: '',

  //   alarm Неисправности
  alrClosed: '/icon/incident/alarm/alrClosed.svg',
  battery: '/icon/incident/alarm/battery.svg',
  connect: '/icon/incident/alarm/connect.svg',
  local: '/icon/incident/alarm/local.svg',
  notTune: '/icon/incident/alarm/notTune.svg',
  fanCrash: '/icon/incident/alarm/alrClosed.svg',
  32: '/icon/incident/alarm/alrClosed.svg',
  33: '/icon/incident/alarm/alrClosed.svg',
  34: '/icon/incident/alarm/alrClosed.svg',
  46: '',
  supply: '',
  bldOff: '',
  gen: '',
  plcio: '',
  66: '',
  93: 'sensor',
  94: '',
  95: '',
  96: '',
  97: '',
  98: '',
  110: '',
  111: '',
  101: '',

  // notification Уведомление
  //   Сушка
  1: '/icon/incident/notification/tout1-1.svg',
  2: '/icon/incident/notification/tout2-1.svg',
  3: '/icon/incident/notification/hout1-2.svg',
  4: '/icon/incident/notification/hout1-1.svg',
  5: '/icon/incident/notification/ahout1-1.svg',
  6: '/icon/incident/notification/ahout2-1.svg',
  // Хранение
  7: '/icon/incident/notification/ahout1.svg',
  8: '/icon/incident/notification/ahout2.svg',
  9: '/icon/incident/notification/hout1.svg',
  10: '/icon/incident/notification/hout2.svg',
  11: '/icon/incident/notification/tout1.svg',
  12: '/icon/incident/notification/tout2.svg',
  16: '/icon/incident/notification/tout3.svg',
  120: '/icon/incident/notification/hout3.svg',
  // Дефростация
  170: '/icon/incident/notification/ahout1.svg',
  171: '/icon/incident/notification/ahout2.svg',
  172: '/icon/incident/notification/hout1.svg',
  173: '/icon/incident/notification/hout2.svg',
  174: '/icon/incident/notification/tout1.svg',
  175: '/icon/incident/notification/tout3.svg',
  176: '/icon/incident/notification/hout3.svg',
};

export default iconIncident;
