const data = {
	alr: '/img/alarm/alr.svg',
	tout: '/img/alarm/temp.svg',
	hout: '/img/alarm/mois.svg',
	ahout: '/img/alarm/mois.svg',
	antibliz: '/img/alarm/wind.svg',
	co2work: '/img/alarm/co2_work.svg',
	co2wait: '/img/alarm/co2_work.svg',
	co2on: '/img/alarm/co2_work.svg',
	openVin: '/img/alarm/open_vin.svg',
	ventOn: '/img/alarm/intfan.svg',
	ventWait: '/img/alarm/intfan.svg',
	ventWork: '/img/alarm/intfan.svg',
	durVentWork: '/img/alarm/dur_vent.svg',
	debdo: '/img/alarm/debdo.svg',
	stableVno: '/img/alarm/hysteresis-fan.svg',
	overVlv: '/img/alarm/valve-crash.svg',
	alrClosed: '/img/alarm/alr.svg',
	alrValve: '/img/alarm/valve-crash.svg',

	drying: '/img/alarm/dry.svg',
	cure: '/img/alarm/healing.svg',
	cooling: '/img/alarm/cooling.svg',
	heat: '/img/alarm/heat.svg',
	vent: '/img/alarm/intfan.svg',
	accel: '/img/alarm/overfan.svg',
	ozon: '/img/alarm/ozon.svg',
	heater: '/img/alarm/heater.svg',
	co2: '/img/alarm/dioxide.svg',
	wetting: '/img/alarm/wetting.svg',

	connect: '/img/alarm/connect.svg',
	local: '/img/alarm/local.svg',
	notTune: '/img/alarm/notTune.svg',
	smoking: '/img/alarm/smoking.svg',
	battery: '/img/alarm/battery.svg',
}
export default data
