const data = {
	alr: '/img/alarm/alr.svg',
	tout: '/img/alarm/temp.svg',
	hout: '/img/alarm/mois.svg',
	ahout: '/img/alarm/mois.svg',
	antibliz: '/img/alarm/wind.svg',
	co2_work: '/img/alarm/co2_work.svg',
	co2_wait: '/img/alarm/co2_work.svg',
	openVin: '/img/alarm/open_vin.svg',
	vent_on: '/img/alarm/intfan.svg',
	vent_dura: '/img/alarm/intfan.svg',
	vent_time_wait: '/img/alarm/intfan.svg',
	vent_time: '/img/alarm/intfan.svg',

	drying: '/img/alarm/dry.svg',
	cure: '/img/alarm/healing.svg',
	cooling: '/img/alarm/cooling.svg',
	heat: '/img/alarm/heat.svg',
	vent: '/img/alarm/intfan.svg',
	accel: '/img/alarm/overfan.svg',
	ozon: '/img/alarm/ozon.svg',
	heater: '/img/alarm/heater.svg',
	co2: '/img/alarm/dioxide.svg',
	wetting: '/img/alarm/wetting.svg',

	connect: '/img/alarm/connect.svg',
	local: '/img/alarm/local.svg',
	smoking: '/img/alarm/smoking.svg',
}
export default data
